      - name: Install Android SDK Build Tools
        run: |
          SDK="$BUILDOZER_HOME/android/platform/android-sdk"
          mkdir -p "$SDK/licenses"

          printf '%s\n' \
          '8933bad161af4178b1185d1a37fbf41ea5269c55' \
          'd56f5187479451eabf01fb78af6dfcb131a6481e' \
          '24333f8a63b6825ea9c5514f83c2829b004d1fee' \
          > "$SDK/licenses/android-sdk-license"

          SDKMANAGER="$SDK/cmdline-tools/latest/bin/sdkmanager"

          if [ ! -f "$SDKMANAGER" ]; then
            echo "sdkmanager not found"
            exit 1
          fi

          yes | "$SDKMANAGER" --licenses || true
          yes | "$SDKMANAGER" "platform-tools" "platforms;android-35" "build-tools;37.0.0"
                - name: Build APK
        run: |
          buildozer -v android debug
